name: Python unittests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: matrix
    python-version: [5.1]

  steps:
  - uses: actions/checkout@v2
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - name: Test
    run: |
      python manage.py test
